name: ai_d_planner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.2
  path_provider: ^2.1.5
  beamer: ^1.7.0
  logger: ^2.5.0
  google_fonts:
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  easy_debounce: ^2.0.3
  intl: ^0.19.0
  flutter_svg: # flutter svg package to use svg assets
  icons_flutter: ^0.0.5 # Icon pack
  easy_localization: ^3.0.7 # for using different local through app
  flutter_app_info: ^3.0.3 # for getting app version and other package related info and device info all in one
  #  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  get_it: ^8.0.3 # dependency injections
  talker_bloc_logger: ^4.6.4
  flutter_app_version_checker: ^0.3.2
  animated_snack_bar: ^0.4.0
  url_launcher: ^6.3.1
  card_swiper: ^3.0.1
  flutter_form_builder: ^9.7.0 # form builder helper
  form_builder_validators: ^11.1.1 # form builder validator use
  smooth_page_indicator: ^1.2.0+3
  pausable_timer: ^3.1.0

  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.1
  package_info_plus: ^8.1.3
  http: ^1.2.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - assets/lottie/
    - assets/png/
    - assets/svg/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.otf
        - asset: assets/fonts/Gilroy-UltraLight.otf
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-Regular.otf
        - asset: assets/fonts/Gilroy-Medium.otf
        - asset: assets/fonts/Gilroy-SemiBold.otf
        - asset: assets/fonts/Gilroy-Bold.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Heavy.otf

    - family: Kalnia
      fonts:
        - asset: assets/fonts/Kalnia-Light.otf
        - asset: assets/fonts/Kalnia-Regular.otf
        - asset: assets/fonts/Kalnia-Medium.otf
        - asset: assets/fonts/Kalnia-SemiBold.otf
        - asset: assets/fonts/Kalnia-Bold.otf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
